/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: kongle (https://sketchfab.com/minecraftnorge)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/earth-63d902b12fd14868b4dc2f19dc21d7c2
Title: Earth
*/

import React, { useRef } from "react";

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { a, useSpring } from "@react-spring/three";

import * as THREE from "three";

function Earth(props) {
  const earthRef = useRef();
  const { nodes, materials } = useGLTF("./earth.glb");

  const { scale } = useSpring({
    from: { scale: [0, 0, 0] },
    to: { scale: [1, 1, 1] },
  });

  useFrame(({ clock }) => {
    const elapsedTime = clock.getElapsedTime();
    earthRef.current.rotation.y = elapsedTime / 10;
  });

  return (
    <a.group ref={earthRef} scale={scale} {...props}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.moon} />
    </a.group>
  );
}

export default Earth;
